#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

# ===-- klee-stats --------------------------------------------------------===##
#
#                      The KLEE Symbolic Virtual Machine
#
#  This file is distributed under the University of Illinois Open Source
#  License. See LICENSE.TXT for details.
#
# ===----------------------------------------------------------------------===##

"""Interface for experimenting with profiling"""

import argparse
import os
import sqlite3
import subprocess
import threading
import time


class KleeStats(object):
    def __init__(self, cursor):
        self.cursor = cursor
        self.cursor.execute("SELECT Instructions, CoveredInstructions, UncoveredInstructions FROM stats ORDER BY Instructions DESC LIMIT 1")

        data = self.cursor.fetchone() 
        self.coveredInstructions = data[1]
        self.uncoveredInstructions = data[2]

    def instructionsCoverage(self):
        return (self.coveredInstructions/(self.coveredInstructions+self.uncoveredInstructions))*100


def run_from_scratch():
    parser = argparse.ArgumentParser(description='Run C program on Klee')
    parser.add_argument('file', type=str, nargs=1, help='.c file or coreutils directory')
    parser.add_argument('profdata', type=str, nargs='*', help='profile data files or folders')
    parser.add_argument('numArgs', type=int , nargs='?', help="Number of sym-args when running with klee")

    args = parser.parse_args()
    file = args.file[0]

    numArgs = args.numArgs[0]
    fileWithoutExt = file.split('.')[0]
    profileData = args.profdata
    mergedProfileFile = "main.profdata"

    #Merge profile data
    os.system("llvm-profdata-6.0 merge -output=" + mergedProfileFile + " " + ' '.join(profileData))

    #Compile C program with merged profile files
    os.system("clang-6.0 -g -fprofile-instr-use=" + mergedProfileFile + " -c -emit-llvm " + file)

    print("File is: ", fileWithoutExt, " and ", file, " and", file.split('.'))

    #Assemble readable asm to .bc- will fail if it already created a .bc file but not issue
    os.system("llvm-as-6.0 " + fileWithoutExt + ".ll")

    #run with klee
    os.system("klee --optimize --libc=uclibc --posix-runtime " + fileWithoutExt + ".bc " + " --sym-arg " + str(numArgs))
    stats = sqlite3.connect("klee-last/run.stats")
    c = stats.cursor()
    statsData = KleeStats(c)
    print("Instruction Coverage Default Searcher: ", statsData.instructionsCoverage())
    #From database need to calculate these values:
    #Branch coverage (need to get this)
    

def getCoverage(path):
    print(path)
    stats = sqlite3.connect(path)
    c = stats.cursor()
    statsData = KleeStats(c)

    return statsData.instructionsCoverage()

def runProgram(kleeCommand, directoryLLVM, directoryGCOV, file):
    process= subprocess.Popen([kleeCommand], shell=True)
    process.wait()
    os.chdir(directoryGCOV)

    #Change this code to the kleestar stuff
    runTests = "klee-replay " + file + " " + directoryLLVM + "/klee-last/*.ktest"
    process=subprocess.Popen([runTests], shell=True)
    process.wait()
    
    runGCOV = "gcov " + file
    process = subprocess.Popen([runGCOV], shell=True, stdout=subprocess.PIPE)
    out, err = process.communicate()
    os.chdir(directoryLLVM)
    
    return out.decode('utf-8')
    
    
#Use gcov for coverage
#Need to instrument c files first
#sort must have --parallel=1
#don't run: kill, chco
def main():
    exclude = ("kill", "chcon", "chown", "chroot", "dd", "ginstall", "stdbuf", 
               "libstdbuf", "rm", "rmdir", "unlink")
    parser = argparse.ArgumentParser(description='Run C program on Klee')
    parser.add_argument('directoryLLVM', type=str, nargs=1, help='directory of bc files')
    parser.add_argument('directoryGCOV', type=str, nargs=1, help='dictory of gcov-instrumented executables')
    
    args = parser.parse_args()
    directoryLLVM = args.directoryLLVM[0]
    directoryGCOV = args.directoryGCOV[0]
    os.chdir(directoryLLVM)
    files = subprocess.run(["ls"], stdout=subprocess.PIPE).stdout.decode('utf-8').split('\n')
    bcFiles = [file for file in files if ".bc" in file]
    cFiles = [file for file in files if ".c" in file]
    os.chdir(directoryGCOV)
    files = subprocess.run(["ls"], stdout=subprocess.PIPE).stdout.decode('utf-8').split('\n')
    gcdaFile = [file for file in files if ".gcda" in file]
    print("gcda: ", gcdaFile)
    os.chdir(directoryLLVM)

    newBcFiles = []
    for file in bcFiles:
        name = file[0:-3]
        noRun = False
        for exc in exclude:
            if exc == name:
                noRun = True
                break
        if noRun:
            continue
        found = False
        for file2 in gcdaFile:
            #print((name,file2[0:-2]))
            if name == file2[0:-5]:
                found = True
                break
        if found:
            newBcFiles += [file]
    bcFiles = newBcFiles
    results = []

    count = 0
    for file in bcFiles:
        if file[0:-3] != "od":
            continue
        path = directoryLLVM+"/"+file
        result = [file]
        print("Running file: ", file)
        #sym-stdout - look it up
        #Use kleestar command on variable 'file'
        runNoProfiling = " klee --max-memory=1000 --disable-inlining\
                          --optimize --libc=uclibc --posix-runtime -external-calls=all\
                          --only-output-states-covering-new --max-sym-array-size=4096\
                          --max-time=3600 --watchdog --switch-type=internal --search=random-path\
                          " + path + " --sym-args 0 1 10 --sym-args 0 2 3\
                          --sym-files 1 8 --sym-stdin 8 --sym-stdout"
        runWithProfiling = "klee --max-memory=1000 --disable-inlining\
                          --optimize --libc=uclibc --posix-runtime -external-calls=all\
                          --only-output-states-covering-new --max-sym-array-size=4096\
                          --max-time=3600 --watchdog --switch-type=internal --search=nurs:bc\
                          " + path + " --sym-args 0 1 10 --sym-args 0 3 4\
                          --sym-files 1 8 --sym-stdin 8 --sym-stdout"

        outProfiling = runProgram(runWithProfiling, directoryLLVM, directoryGCOV, file[0:-3])
        outNoProfiling = runProgram(runNoProfiling, directoryLLVM, directoryGCOV, file[0:-3])
        result += [outProfiling, outNoProfiling]
        results += [result]
        if count == 2:
            break
        count += 1
    for i in results:
        print("File: ", i[0])
        print("With profiling result: ")
        print(i[1])
        print("Without profiling: ")
        print(i[2])
    #print(newBcFiles)

             
           
main()
